import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const defaultSrcDir = resolve(import.meta.dirname, "../src");

const readJson = async (srcDir, fileName) =>
  JSON.parse(await readFile(resolve(srcDir, fileName), "utf-8"));

const appendScale = (cssLines, prefix, scale) => {
  for (const [key, value] of Object.entries(scale)) {
    cssLines.push(`  --snurble-${prefix}-${key}: ${value};`);
  }
};

export const buildGeneratedCss = ({ spacing, typography, radius, zIndex }) => {
  const cssLines = [
    "/* Generated by sync-tokens.js - DO NOT EDIT MANUALLY */",
    "",
    ":root {",
  ];

  for (const [key, value] of Object.entries(spacing.scale)) {
    cssLines.push(
      `  --snurble-space-${key}: calc(${value} * var(--snurble-density-multiplier, 1));`
    );
  }

  appendScale(cssLines, "font", typography.families);

  for (const [styleName, style] of Object.entries(typography.styles)) {
    cssLines.push(`  --snurble-type-${styleName}-size: ${style.size};`);
    cssLines.push(
      `  --snurble-type-${styleName}-line-height: ${style.lineHeight};`
    );
    cssLines.push(`  --snurble-type-${styleName}-weight: ${style.weight};`);
  }

  if (radius?.scale) {
    appendScale(cssLines, "radius", radius.scale);
  }

  if (zIndex?.scale) {
    appendScale(cssLines, "z-index", zIndex.scale);
  }

  cssLines.push("}", "");
  return cssLines.join("\n");
};

export const syncTokens = async ({ srcDir = defaultSrcDir } = {}) => {
  const spacing = await readJson(srcDir, "spacing.json");
  const typography = await readJson(srcDir, "typography.json");

  let radius;
  try {
    radius = await readJson(srcDir, "radius.json");
  } catch {
    radius = undefined;
  }

  let zIndex;
  try {
    zIndex = await readJson(srcDir, "z-index.json");
  } catch {
    zIndex = undefined;
  }

  const cssContent = buildGeneratedCss({ radius, spacing, typography, zIndex });
  await writeFile(resolve(srcDir, "_generated.css"), cssContent);
  console.log("Successfully generated _generated.css");
};

const isDirectExecution =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href;

if (isDirectExecution) {
  try {
    await syncTokens();
  } catch (error) {
    console.error(error);
    process.exitCode = 1;
  }
}
