import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const srcDir = resolve(import.meta.dirname, "../src");

const syncTokens = async () => {
  const spacing = JSON.parse(
    await readFile(resolve(srcDir, "spacing.json"), "utf-8")
  );
  const typography = JSON.parse(
    await readFile(resolve(srcDir, "typography.json"), "utf-8")
  );

  let cssContent =
    "/* Generated by sync-tokens.js - DO NOT EDIT MANUALLY */\n\n:root {\n";

  // Spacing
  for (const [key, value] of Object.entries(spacing.scale)) {
    cssContent += `  --snurble-space-${key}: ${value};\n`;
  }

  // Typography Families
  for (const [key, value] of Object.entries(typography.families)) {
    cssContent += `  --snurble-font-${key}: ${value};\n`;
  }

  // Typography Styles
  for (const [styleName, style] of Object.entries(typography.styles)) {
    cssContent += `  --snurble-type-${styleName}-size: ${style.size};\n`;
    cssContent += `  --snurble-type-${styleName}-line-height: ${style.lineHeight};\n`;
    cssContent += `  --snurble-type-${styleName}-weight: ${style.weight};\n`;
  }

  // Optional: Add radius and z-index if they exist
  try {
    const radius = JSON.parse(
      await readFile(resolve(srcDir, "radius.json"), "utf-8")
    );
    for (const [key, value] of Object.entries(radius.scale)) {
      cssContent += `  --snurble-radius-${key}: ${value};\n`;
    }
  } catch {
    // radius.json might not exist yet
  }

  try {
    const zIndex = JSON.parse(
      await readFile(resolve(srcDir, "z-index.json"), "utf-8")
    );
    for (const [key, value] of Object.entries(zIndex.scale)) {
      cssContent += `  --snurble-z-index-${key}: ${value};\n`;
    }
  } catch {
    // z-index.json might not exist yet
  }

  cssContent += "}\n";

  await writeFile(resolve(srcDir, "_generated.css"), cssContent);
  console.log("Successfully generated _generated.css");
};

try {
  await syncTokens();
} catch (error) {
  console.error(error);
}
